language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode11
    - rust: beta
    - rust: nightly

    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps --all-features
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master

script:
  - cargo test

notifications:
  email:
    on_success: never
